version: '3.7'

services: 
  app-service:
    image: juliuskrah/cdcapp:1.0
    container_name: cdc-service
    build: 
      context: ./app-service
      dockerfile: src/main/docker/Dockerfile
    environment: 
    - POSTGRES_REACTIVE_CLIENT_HOST=postgres
    - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    ports:
    - '8082:8082'
  app-client:
    image: louisga/cdc-client:1.0
    container_name: cdc-client
    build: 
      context: ./app-client
      dockerfile: src/main/docker/Dockerfile
    ports:
    - '8081:8081'
    depends_on:
    - app-service
  postgres:
    image: juliuskrah/postgres:12-alpine-cdc
    container_name: cdc-postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment: 
    - POSTGRES_USER=julius
    - POSTGRES_PASSWORD=julius123
    volumes: 
    - pgdata:/var/lib/postgresql/data
    ports:
    - '5432:5432'
  keycloak:
    image: juliuskrah/keycloak:8.0.1
    container_name: cdc-keycloak
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    depends_on: 
    - postgres
    environment: 
    - KEYCLOAK_USER=juliuskrah
    - KEYCLOAK_PASSWORD=julius123    
    - KEYCLOAK_IMPORT=/tmp/sample_realm.json
    - DB_ADDR=postgres
    - DB_PORT=5432
    - DB_DATABASE=sample
    - DB_SCHEMA=sample
    - DB_USER=sample
    - DB_PASSWORD=sample
    volumes: 
    - ./keycloak:/tmp
    ports:
    - '8080:8080'
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.2
    container_name: cdc-zookeeper
    environment: 
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000
    - ZOOKEEPER_SYNC_LIMIT=2
    volumes: 
    - zk-data:/var/lib/zookeeper/data
    - zk-trx-logs:/var/lib/zookeeper/log
  kafka:
    image: confluentinc/cp-kafka:5.3.2
    container_name: cdc-kafka
    depends_on: 
    - zookeeper
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    - KAFKA_BROKER_ID=1
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes: 
    - kafka-data:/var/lib/kafka/data
    ports: 
    - '9092:9092'
  connect:
    image: debezium/connect:1.0.0.Final
    container_name: cdc-connect
    depends_on: 
    - kafka
    - postgres
    environment:
    - BOOTSTRAP_SERVERS=kafka:29092
    - GROUP_ID=1
    - CONFIG_STORAGE_TOPIC=cdc_connect_configs
    - OFFSET_STORAGE_TOPIC=cdc_connect_offsets
    - STATUS_STORAGE_TOPIC=cdc_connect_statuses
    # volumes: 
    # - ./connect:/scripts
    ports:
    - '8083:8083'

volumes: 
  pgdata:
  zk-data:
  zk-trx-logs:
  kafka-data:
      